# Generated by Django 4.2.10 on 2024-03-16 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expiration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('max_redemptions', models.PositiveIntegerField(default=1)),
                ('times_redeemed', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
