# Generated by Django 4.2.10 on 2024-03-16 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promo',
            old_name='expiration_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='promo',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='promo',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
