# Generated by Django 4.2.10 on 2024-03-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_rename_expiration_date_promo_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
