# Generated by Django 5.0 on 2024-02-12 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_remove_roomtype_total_rooms'),
        ('filters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='adminpanel.roomtype'),
        ),
    ]
