# Generated by Django 5.0 on 2024-02-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0002_alter_booking_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
