# Generated by Django 5.0 on 2024-01-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='total_rooms',
            field=models.IntegerField(),
        ),
    ]
