# Generated by Django 5.0 on 2024-03-29 10:18

import adminpanel.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
        ('book', '0004_remove_order_booking_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='order',
            field=models.ForeignKey(default=adminpanel.models.create_default_order, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='book.order'),
        ),
    ]
