# Generated by Django 5.0 on 2024-02-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='total_rooms',
        ),
    ]
