# Generated by Django 5.0 on 2024-03-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_booking_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out')], default='reserved', max_length=20),
        ),
    ]
