# Generated by Django 5.0 on 2024-04-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
