# Generated by Django 5.0 on 2024-04-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_alter_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurchargeRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_friendly_surcharge', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('smoking_surcharge', models.DecimalField(decimal_places=2, default=200.0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Surcharge Rates',
            },
        ),
    ]
