# Generated by Django 5.0 on 2024-01-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name', max_length=255, verbose_name='Name')),
                ('email', models.EmailField(help_text='Enter the email', max_length=254, unique=True, verbose_name='Email')),
                ('cellNum', models.CharField(help_text='Enter the cell number', max_length=15)),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('message', models.CharField(max_length=255, verbose_name='Message')),
            ],
        ),
    ]
