# Generated by Django 5.0 on 2024-01-04 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='cellNum',
        ),
        migrations.AddField(
            model_name='contact',
            name='cell_num',
            field=models.CharField(default=1, help_text='Enter the cell number', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(help_text='Message', max_length=255, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(help_text='Subject', max_length=255, verbose_name='Subject'),
        ),
    ]
