# Generated by Django 5.0 on 2024-01-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contact_cellnum_contact_cell_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cell_num',
            field=models.CharField(help_text='Enter the cell number', max_length=11),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(help_text='Enter the email', max_length=254, verbose_name='Email'),
        ),
    ]
