# Generated by Django 5.0 on 2024-01-09 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_cell_num_alter_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='cell_num',
        ),
    ]
