# Generated by Django 5.0 on 2024-03-29 10:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_order_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='booking',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
