# Generated by Django 5.0 on 2024-04-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_order_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
